---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 56.6.2
    releaseName: kube-prom
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml

namespace: monitoring